version: "3.9"

services:
  auth-manager:
    build:
      context: ../authorization-manager
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    env_file:
      - ../authorization-manager/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ../authorization-manager/src:/app/src

  api:
    build:
      context: ../Dog-Walking-Service
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db
    env_file:
      - ../Dog-Walking-Service/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ../Dog-Walking-Service/src:/app/src
      - ../Dog-Walking-Service/app.py:/app/app.py

  customers-service:
    build:
      context: ../customers-service
      dockerfile: Dockerfile.dev
    ports:
      - 8060:8060
    depends_on:
      - db
    links:
      - db
    env_file:
      - ../customers-service/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ../customers-service/src:/app/src

  db:
    image: postgres:14.8
    env_file:
      - ./db/.env
    ports:
      - 52000:5432
    volumes:
      - Dog-Walking-App:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  Dog-Walking-App:
